name: Frontend UI Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  playwright:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar dependências
        working-directory: ./tests
        run: npm install

      - name: Instalar Playwright e browsers
        working-directory: ./tests
        run: npx playwright install --with-deps

      - name: Executar testes Playwright
        working-directory: ./tests
        run: npx playwright test
